contract:
  rinkeby:
    account_name: 'rinkeby-account1'
    address: '0xFA8639CD3FF633b2C2AB26CfDAc0FF4ebF6019d3'
    dependencies:
      randomness:
        vrf_coordinator: '0x6168499c0cFfCaCD319c818142124B7A15E857ab'
        link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
        keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
        request_confirmations: 3
        subscription_id: 638

dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.4.0

compiler:
  solc:
    version: 0.8.7
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0'