contract:
  rinkeby:
    account_name: 'rinkeby-account1'
    address: '0xD6E802834282c8C693b3445683af6d2b1f845EAa'
    dependencies:
      randomness:
        vrf_coordinator: '0x6168499c0cFfCaCD319c818142124B7A15E857ab'
        keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
        request_confirmations: 3
        subscription_id: 638
  development:
    dependencies:
      randomness:
        keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
        request_confirmations: 3

dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.4.0

compiler:
  solc:
    version: 0.8.7
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0'